[package]
name = "eks-development"
version = "0.5.9"
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "dev"
test = false

[[bin]]
name = "setup"
test = false

[[bin]]
name = "update_locales"
test = false

[[bin]]
name = "pdf_diff"
test = false

[[bin]]
name = "create_acme_account"
test = false
required-features = ["acme"]

[features]
acme = ["eks/acme"]

[dependencies]
anyhow = { workspace = true }
dotenvy = { workspace = true }
tokio = { workspace = true, features = ["process"] }
serde = { workspace = true }
serde_json = { workspace = true }
saphyr = { workspace = true }
serde-saphyr = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
eks = { path = "..", default-features = false }
eks-locales = { path = "../tools/locales" }

[lints]
workspace = true
