[package]
name = "eks-development"
version = "0.4.13"
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "dev"
test = false

[[bin]]
name = "setup"
test = false

[[bin]]
name = "update_locales"
test = false

[[bin]]
name = "pdf_diff"
test = false

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
saphyr = { workspace = true }
serde-saphyr = { workspace = true }
regex = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
typst-webservice = { workspace = true }
