hostname: "kiesraad.net"
subdomain: "<branchname>"

ingress:
  enabled: false
  class: nginx

gatewayApi:
  enabled: false

typst:
  enabled: true
  image: "ghcr.io/kiesraad/e-ks/typst"

bag:
  image: "ghcr.io/tweedegolf/bag-address-lookup"
  version: "0.3.5"

eks:
  image: "ghcr.io/kiesraad/e-ks/eks"

db:
  image: "ghcr.io/kiesraad/e-ks/db"
  setup: false
  erase: false

  # connection parameters
  host: postgres-cluster-rw
  port: 5432
  user: eks
  database: eks
  password: "supersecurepassword"
