hostname: "kiesraad.net"
subdomain: "<branchname>"
requireLogin: true

ingress:
  enabled: false
  class: nginx

gatewayApi:
  enabled: false

bag:
  image: "ghcr.io/tweedegolf/bag-address-lookup"
  version: "0.3.3"

eks:
  image: "ghcr.io/kiesraad/e-ks/eks-core"

db:
  setup: false
  erase: false
  runMigrations: false

  # connection parameters
  host: postgresql.postgresql.svc.cluster.local
  port: 5432
  user: postgres
  password: "supersecurepassword"
