[package]
name = "module_dependency_cycles"
version = "0.1.0"
description = "Reject cyclic dependencies between components"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
dylint_linting = "=6.0.3"

[workspace]

[lints.clippy]
unwrap_used = "warn"
cognitive_complexity = "warn"
too_many_lines = "warn"
empty_line_after_outer_attr = "warn"
redundant_closure_for_method_calls = "warn"
redundant_else = "warn"
wildcard_imports = "warn"

[package.metadata.rust-analyzer]
rustc_private = true
