changelog:
  categories:
    - title: Fixed Issues
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
        authors:
          - dependabot
    - title: Updated Dependencies
      labels:
        - dependencies
