comment:
  layout: "diff, files"
  require_changes: false
  require_base: false
  require_head: false
  hide_project_coverage: false
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
