services:
  psql:
    image: ghcr.io/tweedegolf/postgres:18
    command: ["postgres", "-c", "log_min_messages=fatal"]
    environment:
      POSTGRES_USER: eks
      POSTGRES_DB: eks
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: Europe/Amsterdam
    ports: ['127.0.0.1:5432:5432']
    networks: [default]

  saml-test-server:
    build:
      context: development
      dockerfile: saml-test-server.Dockerfile
    ports: ['127.0.0.1:8080:8080']
    networks: [default]
