sonar.projectKey=kiesraad_e-ks
sonar.organization=kiesraad
sonar.tests=playwright/tests
sonar.test.inclusions=playwright/tests/**/*.ts
sonar.exclusions=target/**,frontend/static/**,**/node_modules/**,**/playwright-report/**,**/playwright/test-results/**
sonar.sources=./
