providers:
  kubernetesCRD:
    allowCrossNamespace: true
  kubernetesGateway:
    enabled: true
  kubernetesIngress:
    enabled: false
  kubernetesIngressNginx:
    enabled: false

service:
  annotations:
    service.beta.kubernetes.io/scw-loadbalancer-type: lb-s
    #                                                    195.154.73.203                       2001:bc8:710:1c::
    service.beta.kubernetes.io/scw-loadbalancer-ip-ids: "bb2c086f-3193-4b78-a028-92d683d85cf1,79c0fc5a-d97f-47f3-a292-7d39787d7d79"

gateway:
  name: "traefik"
  listeners:
    web:
      port: 8000
      protocol: HTTP
      namespacePolicy:
        from: All
    websecure:
      port: 8443
      protocol: HTTPS
      certificateRefs:
        - kind: Secret
          name: eks-tls-cert
      namespacePolicy:
        from: All

gatewayClass:
  name: "traefik"


deployment:
  replicas: 2
