user www-data;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 9001;
        server_name _;

        location = / {
            return 302 /simplesaml/;
        }

        location /simplesaml/ {
            alias /opt/simplesamlphp/public/;
            index index.php;
            try_files $uri $uri/ /simplesaml/index.php$is_args$args;
        }

        location ~ ^/simplesaml/(?<phpfile>.+?\.php)(?<pathinfo>/.*)?$ {
            alias /opt/simplesamlphp/public/$phpfile;

            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /opt/simplesamlphp/public/$phpfile;
            fastcgi_param SCRIPT_NAME /simplesaml/$phpfile;
            fastcgi_param PATH_INFO $pathinfo;
            fastcgi_param PATH_TRANSLATED /opt/simplesamlphp/public$pathinfo;

            fastcgi_pass 127.0.0.1:9000;
        }
    }
}
