apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: eks
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: core
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: eks
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eks
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        ingress-controller-frontoffice-policy: allow
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: regcred
      containers:
        - name: eks
          image: "{{ .Values.eks.image }}:{{ .Chart.AppVersion }}"
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: database_url
          resources:
            limits:
              memory: "50Mi"
            requests:
              cpu: "10m"
              memory: "10Mi"
              ephemeral-storage: "512Mi"
