apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: eks-http
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: traefik
      namespace: ingress
      sectionName: web
      kind: Gateway

  hostnames:
    - {{ include "fullHostname" . }}

  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: eks-https
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: traefik
      sectionName: websecure
      namespace: ingress
      kind: Gateway

  hostnames:
    - {{ include "fullHostname" . }}

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /lookup
        - path:
            type: PathPrefix
            value: /suggest

      backendRefs:
        - name: bag-lookup
          port: 80

    - matches:
        - path:
            type: PathPrefix
            value: /

      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: security-headers
  {{- if .Values.requireLogin }}
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: auth
  {{- end }}

      backendRefs:
        - name: eks
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: {{ .Release.Namespace }}
spec:
  chain:
    middlewares:
      - name: auth-error-redirection
        namespace: ingress
      - name: test-auth
        namespace: ingress
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    frameDeny: true
    contentTypeNosniff: true
    contentSecurityPolicy: "default-src 'none'; base-uri 'none'; connect-src: 'self'; form-action 'self' https://github.com/login/oauth/authorize; script-src 'self'; style-src 'self' 'unsafe-hashes' 'sha256-f5JbnZ2wnky3B/YgIC+GaLDK8cBvQj7OEOASYhBjUYA=' 'sha256-be2laphxFXcKr/3rNHrcGPm2jpf+OrcryYe8Gxt//J8='; font-src 'self'; img-src 'self'; frame-ancestors 'none';"
    referrerPolicy: same-origin

    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsSeconds: 31536000
    stsPreload: false # in production, we should consider setting this to true
