INSERT INTO persons (
    id,
    gender,
    last_name,
    last_name_prefix,
    first_name,
    initials,
    date_of_birth,
    bsn,
    place_of_residence,
    country_of_residence,
    locality,
    postal_code,
    house_number,
    house_number_addition,
    street_name,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING
    id,
    gender as "gender: Gender",
    last_name,
    last_name_prefix,
    first_name,
    initials,
    date_of_birth,
    bsn,
    place_of_residence,
    country_of_residence,
    locality,
    postal_code,
    house_number,
    house_number_addition,
    street_name,
    created_at,
    updated_at
