UPDATE persons
SET
    gender = $1,
    last_name = $2,
    last_name_prefix = $3,
    first_name = $4,
    initials = $5,
    date_of_birth = $6,
    bsn = $7,
    no_bsn_confirmed = $8,
    place_of_residence = $9,
    country_of_residence = $10,
    updated_at = NOW()
WHERE id = $11
RETURNING
    id,
    gender as "gender: Gender",
    last_name,
    last_name_prefix,
    first_name,
    initials,
    date_of_birth,
    bsn,
    no_bsn_confirmed,
    place_of_residence,
    country_of_residence,
    representative_last_name,
    representative_last_name_prefix,
    representative_initials,
    locality,
    postal_code,
    house_number,
    house_number_addition,
    street_name,
    created_at,
    updated_at
