use std::str::FromStr;

use crate::{form::ValidationError, transparent_string};

transparent_string! {
    pub struct LastNamePrefix(String);
}

impl FromStr for LastNamePrefix {
    type Err = ValidationError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        let trimmed_value = value.trim();

        if !LAST_NAME_PREFIXES.contains(&trimmed_value) {
            return Err(ValidationError::InvalidValue);
        }

        Ok(LastNamePrefix(trimmed_value.to_string()))
    }
}

pub(crate) fn is_last_name_prefix(value: &str) -> bool {
    LAST_NAME_PREFIXES.contains(&value)
}

/// Split a written-out last name into its prefix and the name itself, taking
/// the longest prefix from the table that the value starts with (prefixes such
/// as "voor in 't" span several words).
#[cfg(any(feature = "fixtures", test))]
pub fn split_last_name_prefix(value: &str) -> (Option<&str>, &str) {
    let value = value.trim();
    let split = value
        .match_indices(' ')
        .filter(|(index, _)| is_last_name_prefix(&value[..*index]))
        .map(|(index, _)| index)
        .next_back();

    match split {
        Some(index) => (Some(&value[..index]), value[index..].trim_start()),
        None => (None, value),
    }
}

/// All prefixes from Table 36 of the [RvIG](https://publicaties.rvig.nl/landelijke-tabellen-32-tm-61)
///
/// (last updated: 27 november 2015)
const LAST_NAME_PREFIXES: [&str; 333] = [
    "A",
    "a",
    "aan",
    "Aan",
    "aan de",
    "Aan de",
    "aan den",
    "Aan den",
    "aan der",
    "Aan der",
    "Aan het",
    "aan het",
    "Aan t",
    "aan t",
    "aan 't",
    "Aan 't",
    "Af",
    "af",
    "al",
    "Al",
    "am",
    "Am",
    "am de",
    "Am de",
    "auf",
    "Auf",
    "auf dem",
    "Auf dem",
    "auf den",
    "Auf den",
    "auf der",
    "Auf der",
    "auf ter",
    "Auf ter",
    "Aus",
    "aus",
    "aus dem",
    "Aus dem",
    "Aus den",
    "aus den",
    "Aus der",
    "aus der",
    "aus m",
    "Aus m",
    "Aus 'm",
    "aus 'm",
    "Ben",
    "ben",
    "bij",
    "Bij",
    "Bij de",
    "bij de",
    "bij den",
    "Bij den",
    "Bij het",
    "bij het",
    "bij t",
    "Bij t",
    "bij 't",
    "Bij 't",
    "bin",
    "Bin",
    "boven d",
    "Boven d",
    "boven d'",
    "Boven d'",
    "d",
    "D",
    "D'",
    "d'",
    "Da",
    "da",
    "Dal",
    "dal",
    "dal'",
    "Dal'",
    "Dalla",
    "dalla",
    "das",
    "Das",
    "de",
    "De",
    "de die",
    "De die",
    "de die le",
    "De die le",
    "de l",
    "De l",
    "de l'",
    "De l'",
    "de la",
    "De la",
    "de las",
    "De las",
    "De le",
    "de le",
    "de van der",
    "De van der",
    "deca",
    "Deca",
    "Degli",
    "degli",
    "Dei",
    "dei",
    "del",
    "Del",
    "Della",
    "della",
    "den",
    "Den",
    "Der",
    "der",
    "des",
    "Des",
    "di",
    "Di",
    "die le",
    "Die le",
    "do",
    "Do",
    "don",
    "Don",
    "dos",
    "Dos",
    "du",
    "Du",
    "el",
    "El",
    "Het",
    "het",
    "i",
    "I",
    "im",
    "Im",
    "In",
    "in",
    "In de",
    "in de",
    "In den",
    "in den",
    "in der",
    "In der",
    "in het",
    "In het",
    "in t",
    "In t",
    "In 't",
    "in 't",
    "L",
    "l",
    "L'",
    "l'",
    "la",
    "La",
    "Las",
    "las",
    "le",
    "Le",
    "les",
    "Les",
    "lo",
    "Lo",
    "Los",
    "los",
    "Of",
    "of",
    "Onder",
    "onder",
    "onder de",
    "Onder de",
    "onder den",
    "Onder den",
    "onder het",
    "Onder het",
    "onder t",
    "Onder t",
    "onder 't",
    "Onder 't",
    "op",
    "Op",
    "op de",
    "Op de",
    "Op den",
    "op den",
    "op der",
    "Op der",
    "Op gen",
    "op gen",
    "op het",
    "Op het",
    "op t",
    "Op t",
    "op 't",
    "Op 't",
    "op ten",
    "Op ten",
    "Over",
    "over",
    "over de",
    "Over de",
    "over den",
    "Over den",
    "over het",
    "Over het",
    "over t",
    "Over t",
    "over 't",
    "Over 't",
    "s",
    "S",
    "'s",
    "'S",
    "s'",
    "S'",
    "t",
    "T",
    "'t",
    "'T",
    "Te",
    "te",
    "ten",
    "Ten",
    "ter",
    "Ter",
    "Tho",
    "tho",
    "Thoe",
    "thoe",
    "thor",
    "Thor",
    "to",
    "To",
    "Toe",
    "toe",
    "Tot",
    "tot",
    "uijt",
    "Uijt",
    "Uijt de",
    "uijt de",
    "Uijt den",
    "uijt den",
    "Uijt 't",
    "uijt 't",
    "uijt te de",
    "Uijt te de",
    "uijt ten",
    "Uijt ten",
    "uit",
    "Uit",
    "Uit de",
    "uit de",
    "uit den",
    "Uit den",
    "uit het",
    "Uit het",
    "uit t",
    "Uit t",
    "uit 't",
    "Uit 't",
    "Uit te de",
    "uit te de",
    "Uit ten",
    "uit ten",
    "Unter",
    "unter",
    "van",
    "Van",
    "Van de",
    "van De",
    "van de",
    "van de l",
    "Van de l",
    "Van de l'",
    "van de l'",
    "van den",
    "Van Den",
    "Van den",
    "van der",
    "Van der",
    "Van Der",
    "van gen",
    "Van gen",
    "van het",
    "Van het",
    "van la",
    "Van la",
    "van t",
    "Van t",
    "Van 't",
    "van 't",
    "Van ter",
    "van ter",
    "Van van de",
    "van van de",
    "ver",
    "Ver",
    "Vom",
    "vom",
    "von",
    "Von",
    "von dem",
    "Von dem",
    "von den",
    "Von den",
    "Von der",
    "von der",
    "Von t",
    "von t",
    "Von 't",
    "von 't",
    "voor",
    "Voor",
    "Voor de",
    "voor de",
    "Voor den",
    "voor den",
    "voor in t",
    "Voor in t",
    "voor in 't",
    "Voor in 't",
    "Voor 't",
    "voor 't",
    "vor",
    "Vor",
    "vor der",
    "Vor der",
    "Zu",
    "zu",
    "zum",
    "Zum",
    "zur",
    "Zur",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn splits_off_the_longest_matching_prefix() {
        assert_eq!(split_last_name_prefix("Bruin"), (None, "Bruin"));
        assert_eq!(split_last_name_prefix("de Bruin"), (Some("de"), "Bruin"));
        assert_eq!(
            split_last_name_prefix("van der Wiel"),
            (Some("van der"), "Wiel")
        );
        assert_eq!(
            split_last_name_prefix("voor in 't C"),
            (Some("voor in \'t"), "C")
        );
    }

    #[test]
    fn leaves_a_name_that_merely_starts_like_a_prefix_alone() {
        assert_eq!(
            split_last_name_prefix("Jansen-de Groot"),
            (None, "Jansen-de Groot")
        );
    }
}
