name: Erase test environment
run-name: 'Erase "${{ github.ref_name }}" test environment'

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  canonical-name:
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.branch-name.outputs.branch-name }}
    steps:
      - uses: actions/checkout@v6
      - name: Canonical branch name
        id: branch-name
        shell: bash
        run: |
          branch_name_without_prefix="${{ github.head_ref || github.ref_name }}"
          
          # Replace all remaining forward slashes '/' with hyphens '-'
          canonical_branch_name=${branch_name_without_prefix//\//-}
          
          # Set the output variable
          echo "branch-name=$canonical_branch_name" >> "$GITHUB_OUTPUT"

  helm-uninstall:
    name: Helm uninstall
    runs-on: ubuntu-latest
    needs: canonical-name
    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig
    environment:
      url: https://${{ needs.canonical-name.outputs.branch-name }}.eks-test.nl
      name: staging
    steps:
      - name: Install Helm
        run: "curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | bash"
      - name: Create kubeconfig file
        run: echo "${{ secrets.KUBECONFIG }}" > ${{ github.workspace }}/kubeconfig
      - name: Helm uninstall
        run: helm uninstall e-ks -n ${{ needs.canonical-name.outputs.branch-name }} --wait
      - name: Delete namespace
        run: kubectl delete namespace ${{ needs.canonical-name.outputs.branch-name }}
