name: Check newline at the end of files

permissions: {}
concurrency:
  group: 
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-newline
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  newline:
    name: Check every file has a newline at the end
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Check newline
        shell: bash
        run: ./bin/check_newline
