name: Check newline at the end of files
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  newline:
    name: Check every file has a newline at the end
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6
      - name: Check newline
        shell: bash
        run: ./bin/check_newline
