name: PR checks

permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft


jobs:
  link-issues:
    if: github.event.pull_request.draft == false
    name: Link issues named in PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Need to be able to edit the PR body
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Add "Closes #N" for issues in PR title
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const fn = require('./.github/scripts/link-issues-to-pr.js')
            await fn({ github, context, core })
        env:
          TITLE: ${{ github.event.pull_request.title }}

  all-checkboxes-checked:
    if: github.event.pull_request.draft == false
    name: All checkboxes of the DoD checklist have been checked
    runs-on: ubuntu-latest
    steps:
      - name: All checkboxes checked in PR body
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const body = context.payload.pull_request.body || '';
            const unchecked = (body.match(/- \[ \]/g) || []).length;
            if (unchecked > 0) {
              core.setFailed(`${unchecked} unchecked item(s) in PR checklist`);
            }
