name: Sigrid PR Feedback

permissions: {}
concurrency:
  group: 
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-sigrid-pr-feedback
  cancel-in-progress: true

on:
  pull_request:

jobs:
  sigridci:
    name: Sigrid CI
    if: "!github.event.pull_request.head.repo.fork"
    environment: development
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # to add a comment with the sigrid results
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@db21307124a69dda204bd2dee751ece097b3d8a3 # main
        continue-on-error: true # a failed quality gate should not fail the job
        with:
          customer: kiesraad
          system: e-ks
          convert: rust
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"

      - name: "Sigrid PR feedback"
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        if: always()
        with:
          script: |
            const commentSigridFeedback = require('./.github/scripts/comment-sigrid-feedback');
            await commentSigridFeedback({ github, context });
