name: Sigrid Publish

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  sigridci:
    if: github.repository == 'kiesraad/e-ks'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6

      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@e93d88a980ff32a67101c070afe1f57c03edb19c # main
        with:
          customer: kiesraad
          system: e-ks
          convert: rust
          publishonly: true
          exclude: deploy,playwright,validate,frontend/styles,src/fixtures,locales
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
