name: Sigrid Publish

permissions:
  contents: read
concurrency:
  group: 
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-sigrid-publish
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  sigridci:
    name: Sigrid CI
    if: github.repository == 'kiesraad/e-ks'
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@8f05c5bd3d3a90a9972faca536ffab14749c4968 # main
        with:
          customer: kiesraad
          system: e-ks
          convert: rust
          publishonly: true
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
