name: Sigrid PR Feedback

permissions: {}
concurrency:
  group: 
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-sigrid-pr-feedback
  cancel-in-progress: true

on:
  pull_request:

jobs:
  sigridci:
    name: Sigrid CI
    if: "!github.event.pull_request.head.repo.fork"
    environment: development
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # to add a comment with the sigrid results
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@e9ccae7ea928e73f58321d46778a395ba7670717 # main
        with:
          customer: kiesraad
          system: e-ks
          convert: rust
          exclude: deploy,playwright,validate,frontend/styles,src/fixtures,locales
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"

      - name: "Sigrid PR feedback"
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        if: always()
        with:
          script: |
            const commentSigridFeedback = require('./.github/scripts/comment-sigrid-feedback');
            await commentSigridFeedback({ github, context });
