name: Sigrid Publish

permissions:
  contents: read
concurrency:
  group: 
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-sigrid-publish
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  sigridci:
    name: Sigrid CI
    if: github.repository == 'kiesraad/e-ks'
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@299e232e03a10a2f5db48bc0c9a3bc5b5dc6f52d # main
        with:
          customer: kiesraad
          system: e-ks
          convert: rust
          publishonly: true
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
