name: Sigrid PR Feedback

on:
  pull_request:

jobs:
  sigridci:
    if: "!github.event.pull_request.head.repo.fork"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6

      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@c0fdc7ff036170d6b39216620b9ac5259532a2cf # main
        with:
          customer: kiesraad
          system: e-ks
          convert: rust
          exclude: deploy,playwright,validate,frontend/styles,src/fixtures,locales
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"

      - name: "Sigrid PR feedback"
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
        if: always()
        with:
          message-id: sigrid
          message-path: sigrid-ci-output/feedback.md
