name: SonarQube

permissions:
  contents: read
concurrency:
  group: 
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-sonarqube
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    permissions:
      contents: read
    environment: development
    runs-on: ubuntu-24.04
    env:
      CARGO_TERM_COLOR: always
      TZ: "Europe/Amsterdam"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: '0'
          persist-credentials: false

      # Branch coverage requires Rust nightly: https://github.com/taiki-e/cargo-llvm-cov/issues/8
      - name: Setup Rust Nightly
        shell: bash
        run: >
          rustup update nightly &&
          rustup default nightly

      - name: Cargo cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          shared-key: eks-sonarqube

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@e67fa11c4b9316fa714ddf0abed07a0c3143b95b # v2.87.4
        with:
          tool: cargo-llvm-cov

      - name: Tools cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: bin
          key: tools-cache-v1-${{ runner.os }}-${{ hashFiles('development/Cargo.toml', 'development/src/**/*.rs', 'development/*.yml') }}

      - name: Setup project
        run: bin/init

      - name: Generate code coverage
        run: cargo llvm-cov --locked --all-features --workspace --lcov --output-path lcov.info

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.rust.lcov.reportPaths=lcov.info
